name: Deploy Azure Function with Terraform

on:
  workflow_dispatch:

env:
  TF_VERSION: '1.7.5'
  AZURE_FUNCTION_DIR: './infra'  # Terraform code location
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    outputs:
      function_app_name: ${{ steps.tf_output.outputs.function_app_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: ${{ env.AZURE_FUNCTION_DIR }}
        run: terraform init

      - name: Terraform Format
        working-directory: ${{ env.AZURE_FUNCTION_DIR }}
        run: terraform fmt -recursive

      - name: Terraform Validate
        working-directory: ${{ env.AZURE_FUNCTION_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.AZURE_FUNCTION_DIR }}
        run: terraform plan -var="client_id=${{ secrets.ARM_CLIENT_ID }}" -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"

      - name: Terraform Apply
        working-directory: ${{ env.AZURE_FUNCTION_DIR }}
        run: terraform apply -auto-approve -var="client_id=${{ secrets.ARM_CLIENT_ID }}" -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"

      - name: Get Function App Name from Terraform Output
        id: tf_output
        working-directory: ${{ env.AZURE_FUNCTION_DIR }}
        run: |
            echo "FUNCTION_APP_NAME=$(terraform output -raw function_app_name)" >> $GITHUB_OUTPUT

  publish:
    name: Deploy Function Code
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Write Function App Name from Terraform Output
        id: tf_output_write
        run: echo "name of func -> ${{ needs.terraform.outputs.function_app_name }}"
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # or '6.0.x'

      - name: Build Function App
        run: |
          dotnet publish ./func/MyDotNetFunctionApp.csproj -c Release -o published

      - name: Zip package
        run: |
          cd published && zip -r ../function.zip .

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ needs.terraform.outputs.function_app_name }}
          package: function.zip
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

